### ISSUE TITLE
Update to 5.0

### ISSUE THREAD

**Issue by Mara-Li** [canisminor1990/ffxiv-cmskin#11]
Please, can you update this wonderfull overlay to 5.0, with DNC/GNB icon ? :> thanks

**Comment by AngeredSpace** [comment]
Bump

**Comment by Mara-Li** [comment]
I don't think we will have an update. The last was in 2017. Maybe someone can re-take the project just for maj ? I don't know how to do it because it's a language/methods i don't know :'(
