### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by kirinelf** [canisminor1990/ffxiv-cmskin#3]
This looks like an amazing skin, with the bar graphs and whatnot. What are the chances of there being an English translation?

**Comment by canisminor1990** [comment]
well, it's in my Todo list, maybe the translation will be ADD in the next version 😘

**Comment by canisminor1990** [comment]
Done

**Comment by kirinelf** [comment]
Oh wow that was REALLY fast! From your last reply, I mean. Much thanks!
