### ISSUE TITLE
折叠菜单报错

### ISSUE THREAD

**Issue by jffifa** [canisminor1990/ffxiv-cmskin#5]
安装ACT后没有做其他配置，DPS统计模板设为你的html，打开面板后右键点`折叠菜单`，报如下错误（chrome console）
```
TypeError: Cannot read property 'tab' of null(…)
f @ common.346d5007a9642d4f9ce7.js:1
Uncaught TypeError: Cannot read property 'tab' of null
```
因为你的代码compile过，所以具体看不出是哪里的问题。

ACT版本为NGA提供的整合版，版本号1.0.2 Release 401
你的插件版本为2.1.7

**Comment by canisminor1990** [comment]
已修复，暂时移出折叠菜单选项，之后打算做成更小的折叠，如折叠成一个Icon然后点击还原，现有折叠占屏依然过大。
